[package]
name = "bitcons-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bitcons"
path = "src/lib.rs"

[[bin]]
name = "bitcons-rs"
path = "src/main.rs"

[dependencies]
